### PR TITLE
Set grid row max widths

### PR DESCRIPTION
**Pull request by adgad**
Makes the grid smaller as per Simon wishes /cc @wheresrhys @matthew-andrews

### CODE REVIEW

**Comment by matthew-andrews** [comment]
i thoguht we were going to fix this by using the new o-grids?

**Comment by matthew-andrews** [comment]
cc @kaelig

**Comment by kaelig** [comment]
Feel free to experiment with the beta: `bower install Financial-Times/o-grid#3.0.0-beta.2`

**Comment by wheresrhys** [comment]
@kaelig - will grid v3 have the ability to set a smaller global max width?

**Comment by wheresrhys** [comment]
> i thoguht

The new dairy based desert from apple @matthew-andrews

**Comment by kaelig** [comment]
I spoke with Simon and since this is a hack until your team actually implements the new grid feel free to merge.

You can also try with 970px which is the size that will be used with o-grid v3.

**Comment by adgad** [comment]
Merging with 970, until we explore some other options.

**Pull request merged**
